const DEFAULT_LIB  = ['Squat','Leg press','Hip thrust','Fente avant','Romanian deadlift','Step-up','Single leg squat','Leg extension','Leg curl','Ischio allongé','Mollet debout','Planche','Gainage latéral','Dead bug','Bird dog','Vélo ergomètre','Tapis de marche','Proprioception plateau','Chaise murale','Pont fessier'];

// ════════════════════════════════════════════════════════════
// BIBLIOTHÈQUE EBP — 200+ exercices structurés (PDF Training Thérapie)
// ════════════════════════════════════════════════════════════
const EBP_REGIONS = [
  {id:'all',   label:'Tous',           color:'#555555'},
  {id:'H',     label:'Hanche',         color:'#2E6B56'},
  {id:'G',     label:'Genou',          color:'#3A6FA8'},
  {id:'C',     label:'Cheville',       color:'#1A7A7A'},
  {id:'E',     label:'Épaule',         color:'#8A3A8A'},
  {id:'Co',    label:'Coude',          color:'#C06030'},
  {id:'P',     label:'Poignet/Main',   color:'#9A7A20'},
  {id:'L',     label:'Lombaire',       color:'#B03A3A'},
  {id:'T',     label:'Thoracique',     color:'#507A20'},
  {id:'Cv',    label:'Cervical',       color:'#6A50A0'},
  {id:'Tr',    label:'Tronc/Gainage',  color:'#A86020'},
  {id:'perso', label:'Mes exercices',  color:'#7B7168'},
];

const EBP_LIB = [
  // HANCHE
  {fr:'Hip Thrust (barre)',           en:'Hip Thrust – Barbell',              region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Hip Thrust (haltère)',         en:'Hip Thrust – Dumbbell',             region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Glute Bridge bilatéral',       en:'Glute Bridge',                      region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Glute Bridge unipodal',        en:'Single Leg Glute Bridge',           region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Squat',                        en:'Squat',                             region:'H',  type:'Poly', phase:'1+2+3'},
  {fr:'Goblet Squat',                 en:'Goblet Squat',                      region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Fentes avant',                 en:'Forward Lunge',                     region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Fentes arrière',               en:'Reverse Lunge',                     region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Bulgarian Split Squat',        en:'Bulgarian Split Squat',             region:'H',  type:'Poly', phase:'1+2+3'},
  {fr:'Arabesques (Single Leg RDL)',   en:'Single Leg Romanian Deadlift',      region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Soulevé de terre roumain',     en:'Romanian Deadlift',                 region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Soulevé de terre',             en:'Deadlift',                          region:'H',  type:'Poly', phase:'2+3'},
  {fr:'Soulevé de terre sumo',        en:'Sumo Deadlift',                     region:'H',  type:'Poly', phase:'2+3'},
  {fr:'Abduction hanche cable',       en:'Hip Abduction – Cable/Band',        region:'H',  type:'Mono', phase:'1+2'},
  {fr:'Adduction hanche cable',       en:'Hip Adduction – Cable/Band',        region:'H',  type:'Mono', phase:'1+2'},
  {fr:'Rotation externe hanche',      en:'Hip External Rotation – Band',      region:'H',  type:'Mono', phase:'1+2'},
  {fr:'Extension hanche cable',       en:'Hip Extension – Cable',             region:'H',  type:'Mono', phase:'1+2'},
  {fr:'Flexion hanche cable',         en:'Hip Flexion – Cable',               region:'H',  type:'Mono', phase:'1+2'},
  {fr:'Clamshell',                    en:'Clamshell',                         region:'H',  type:'Mono', phase:'1'},
  {fr:'Clamshell lesté',              en:'Weighted Clamshell',                region:'H',  type:'Mono', phase:'1+2'},
  {fr:'Kick-back fessier',            en:'Donkey Kick / Glute Kickback',      region:'H',  type:'Mono', phase:'1+2'},
  {fr:'Fire Hydrant',                 en:'Fire Hydrant',                      region:'H',  type:'Mono', phase:'1+2'},
  {fr:'Abduction hanche couché',      en:'Side Lying Hip Abduction',          region:'H',  type:'Mono', phase:'1+2'},
  {fr:'Squat bulgare isométrique',    en:'Isometric Bulgarian Split Squat',   region:'H',  type:'Iso',  phase:'1'},
  {fr:'Hip Thrust isométrique',       en:'Isometric Hip Thrust',              region:'H',  type:'Iso',  phase:'1'},
  {fr:'Step-up',                      en:'Step-Up',                           region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Step-up latéral',              en:'Lateral Step-Up',                   region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Fentes latérales',             en:'Lateral Lunge / Side Lunge',        region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Good morning',                 en:'Good Morning',                      region:'H',  type:'Poly', phase:'1+2'},
  {fr:'Deadlift déficit',             en:'Deficit Deadlift',                  region:'H',  type:'Poly', phase:'2+3'},
  {fr:'Hip Circle (mobilité)',        en:'Hip Circle / CARs',                 region:'H',  type:'Mob',  phase:'1'},
  // GENOU
  {fr:'Leg extension',                en:'Leg Extension',                     region:'G',  type:'Mono', phase:'1+2'},
  {fr:'Leg curl allongé',             en:'Lying Leg Curl',                    region:'G',  type:'Mono', phase:'1+2'},
  {fr:'Leg curl assis',               en:'Seated Leg Curl',                   region:'G',  type:'Mono', phase:'1+2'},
  {fr:'Nordic Curl',                  en:'Nordic Hamstring Curl',             region:'G',  type:'Mono', phase:'2+3'},
  {fr:'Good morning (genou)',         en:'Good Morning',                      region:'G',  type:'Poly', phase:'1+2'},
  {fr:'Squat (genou)',                en:'Squat',                             region:'G',  type:'Poly', phase:'1+2+3'},
  {fr:'Bulgarian Split Squat (genou)',en:'Bulgarian Split Squat',             region:'G',  type:'Poly', phase:'1+2+3'},
  {fr:'Fentes (genou)',               en:'Lunges',                            region:'G',  type:'Poly', phase:'1+2'},
  {fr:'Step-down excentrique',        en:'Step-Down / Eccentric Step',        region:'G',  type:'Poly', phase:'1+2'},
  {fr:'Step-up (genou)',              en:'Step-Up',                           region:'G',  type:'Poly', phase:'1+2'},
  {fr:'Chaise murale (Wall Sit)',     en:'Wall Sit',                          region:'G',  type:'Iso',  phase:'1'},
  {fr:'Squat isométrique',            en:'Isometric Squat Hold',              region:'G',  type:'Iso',  phase:'1'},
  {fr:'Terminal Knee Extension',      en:'Terminal Knee Extension – Band',    region:'G',  type:'Mono', phase:'1+2'},
  {fr:'Leg press',                    en:'Leg Press',                         region:'G',  type:'Poly', phase:'1+2'},
  {fr:'Sissy Squat',                  en:'Sissy Squat',                       region:'G',  type:'Poly', phase:'1+2'},
  {fr:'Hack Squat',                   en:'Hack Squat',                        region:'G',  type:'Poly', phase:'1+2'},
  {fr:'Spanish Squat',                en:'Spanish Squat – Band',              region:'G',  type:'Iso',  phase:'1'},
  {fr:'Fente latérale (genou)',       en:'Lateral Lunge',                     region:'G',  type:'Poly', phase:'1+2'},
  {fr:'Gliding Leg Curl',             en:'Gliding Leg Curl',                  region:'G',  type:'Mono', phase:'1+2'},
  {fr:'Régression Nordic Curl',       en:'Nordic Curl Regression',            region:'G',  type:'Mono', phase:'1+2'},
  {fr:'Sauts verticaux',              en:'Jump / Vertical Jump',              region:'G',  type:'Plio', phase:'3'},
  {fr:'Hop tests',                    en:'Hop Tests / Horizontal Hop',        region:'G',  type:'Plio', phase:'3'},
  {fr:'Drop Jump',                    en:'Drop Jump',                         region:'G',  type:'Plio', phase:'3'},
  {fr:'Leg Curl en pont',             en:'Bridge Leg Curl',                   region:'G',  type:'Mono', phase:'1+2'},
  // CHEVILLE
  {fr:'Mollets debout bilatéral',     en:'Standing Calf Raise',               region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Mollets debout unipodal',      en:'Single Leg Calf Raise',             region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Mollets assis (soléaire)',     en:'Seated Calf Raise',                 region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Mollets excentriques Alfredson',en:'Eccentric Heel Drop – Alfredson',  region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Tibia raise',                  en:'Tibialis Raise / Tib Bar Raise',    region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Éversion cheville élastique',  en:'Ankle Eversion – Band',             region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Inversion cheville élastique', en:'Ankle Inversion – Band',            region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Flexion plantaire élastique',  en:'Plantar Flexion – Band',            region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Flexion dorsale élastique',    en:'Dorsiflexion – Band',               region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Proprioception sol stable',    en:'Single Leg Balance – Stable',       region:'C',  type:'Iso',  phase:'1'},
  {fr:'Proprioception sol instable',  en:'Single Leg Balance – Unstable',     region:'C',  type:'Iso',  phase:'1+2'},
  {fr:'Y-Balance (exercice)',         en:'Y-Balance Reach',                   region:'C',  type:'Iso',  phase:'1+2'},
  {fr:'Saut unipodal stabilisé',      en:'Single Leg Hop – Stick Landing',    region:'C',  type:'Plio', phase:'3'},
  {fr:'Skipping / Montées genoux',    en:'Skipping / High Knees',             region:'C',  type:'Plio', phase:'3'},
  {fr:'Calf press (leg press)',       en:'Calf Press on Leg Press',           region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Towel Scrunches (orteils)',    en:'Towel Toe Curls',                   region:'C',  type:'Mono', phase:'1'},
  {fr:'Toe Spread / Short Foot',      en:'Toe Spread / Short Foot',           region:'C',  type:'Mono', phase:'1'},
  {fr:'Heel Walks',                   en:'Heel Walks',                        region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Toe Walks',                    en:'Toe Walks',                         region:'C',  type:'Mono', phase:'1+2'},
  {fr:'Drop Landing cheville',        en:'Drop Landing – Ankle Focus',        region:'C',  type:'Plio', phase:'3'},
  {fr:'Mobilité tibio-fibulaire',     en:'Banded Ankle Mobilization',         region:'C',  type:'Mob',  phase:'1'},
  {fr:'3D Ankle CARs',                en:'Ankle CARs',                        region:'C',  type:'Mob',  phase:'1'},
  // ÉPAULE
  {fr:'Développé militaire',          en:'Overhead Press / Strict Press',     region:'E',  type:'Poly', phase:'2+3'},
  {fr:'Développé couché barre',       en:'Bench Press',                       region:'E',  type:'Poly', phase:'2+3'},
  {fr:'Développé couché haltères',    en:'Dumbbell Bench Press',              region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Développé incliné',            en:'Incline Press',                     region:'E',  type:'Poly', phase:'2+3'},
  {fr:'Écarté couché (pec fly)',      en:'Dumbbell Fly',                      region:'E',  type:'Mono', phase:'1+2'},
  {fr:'Pull-over haltère',            en:'Dumbbell Pullover',                 region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Rotation externe RE1',         en:'External Rotation – Band (0 deg)',  region:'E',  type:'Mono', phase:'1+2'},
  {fr:'Rotation externe RE2',         en:'External Rotation – Band (90 deg)', region:'E',  type:'Mono', phase:'1+2'},
  {fr:'Rotation interne élastique',   en:'Internal Rotation – Band',          region:'E',  type:'Mono', phase:'1+2'},
  {fr:'Rotation externe couché',      en:'Side Lying External Rotation',      region:'E',  type:'Mono', phase:'1+2'},
  {fr:'Élévations latérales',         en:'Lateral Raise',                     region:'E',  type:'Mono', phase:'1+2'},
  {fr:'Élévations frontales',         en:'Front Raise',                       region:'E',  type:'Mono', phase:'1+2'},
  {fr:'Face Pull',                    en:'Face Pull',                         region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Cuban Press',                  en:'Cuban Press',                       region:'E',  type:'Poly', phase:'1+2'},
  {fr:'W-Y-T prone',                  en:'W-Y-T Raises Prone',                region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Tirage horizontal',            en:'Seated Cable Row',                  region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Tirage poitrine',              en:'Lat Pulldown',                      region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Pull-up / Traction',           en:'Pull-Up / Chin-Up',                 region:'E',  type:'Poly', phase:'2+3'},
  {fr:'Scapular Pull-Up',             en:'Scapular Pull-Up',                  region:'E',  type:'Mono', phase:'1'},
  {fr:'Tirage nuque prise large',     en:'Wide Grip Lat Pulldown',            region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Rowing haltère unilatéral',    en:'Single Arm Dumbbell Row',           region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Rowing barre',                 en:'Barbell Bent-Over Row',             region:'E',  type:'Poly', phase:'2+3'},
  {fr:'Push-up',                      en:'Push-Up',                           region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Push-up décliné',              en:'Decline Push-Up',                   region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Pike Push-Up',                 en:'Pike Push-Up',                      region:'E',  type:'Poly', phase:'1+2'},
  {fr:'Dips',                         en:'Dips',                              region:'E',  type:'Poly', phase:'2+3'},
  {fr:'Band Pull-Apart',              en:'Scapular Retraction – Band',        region:'E',  type:'Mono', phase:'1+2'},
  {fr:'Dépression scapulaire iso',    en:'Scapular Depression Hold',          region:'E',  type:'Iso',  phase:'1'},
  {fr:'Shrug haltères',               en:'Dumbbell Shrug',                    region:'E',  type:'Mono', phase:'1+2'},
  {fr:'CARs épaule',                  en:'Shoulder CARs',                     region:'E',  type:'Mob',  phase:'1'},
  {fr:'Sleeper Stretch (mobilité RI)',en:'Sleeper Stretch',                   region:'E',  type:'Mob',  phase:'1'},
  // COUDE
  {fr:'Curl biceps haltères',         en:'Dumbbell Bicep Curl',               region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Curl biceps barre',            en:'Barbell Curl',                      region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Curl marteau',                 en:'Hammer Curl',                       region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Curl incliné (stretch curl)',  en:'Incline Dumbbell Curl',             region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Curl concentré',               en:'Concentration Curl',                region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Curl câble',                   en:'Cable Curl',                        region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Curl EZ bar',                  en:'EZ Bar Curl',                       region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Curl excentrique',             en:'Eccentric Bicep Curl',              region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Extension triceps poulie haute',en:'Tricep Pushdown – Cable',          region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Extension triceps overhead',   en:'Overhead Tricep Extension',         region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Skull Crushers',               en:'Skull Crushers',                    region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Tricep Kickback',              en:'Tricep Kickback',                   region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Dips triceps banc',            en:'Bench Dips',                        region:'Co', type:'Poly', phase:'1+2'},
  {fr:'Extension triceps excentrique',en:'Eccentric Tricep Extension',        region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Extensions des poignets (épicondylite lat)',en:'Wrist Extension – Dumbbell', region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Flexions des poignets (épicondylite med)',en:'Wrist Flexion – Dumbbell', region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Supination/pronation forearm', en:'Forearm Supination / Pronation',    region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Reverse Curl',                 en:'Reverse Curl',                      region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Tyler Twist excentrique',      en:'Tyler Twist – Eccentric Wrist',     region:'Co', type:'Mono', phase:'1+2'},
  {fr:'Squeeze ball / grip training', en:'Grip Squeeze / Hand Gripper',       region:'Co', type:'Iso',  phase:'1+2'},
  {fr:'Pronation lesté',              en:'Weighted Pronation',                region:'Co', type:'Mono', phase:'1+2'},
  // POIGNET & MAIN
  {fr:'Extension du poignet haltère', en:'Wrist Extension – Dumbbell',        region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Flexion du poignet haltère',   en:'Wrist Flexion – Dumbbell',          region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Supination/pronation',         en:'Forearm Supination / Pronation',    region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Déviation radiale/cubitale',   en:'Radial / Ulnar Deviation',          region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Tyler Twist Flexbar',          en:'Tyler Twist – Flexbar',             region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Extension doigts élastique',   en:'Finger Extension – Band',           region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Flexion doigts (grip)',        en:'Finger Flexion / Grip Training',    region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Pince pollici-digitale',       en:'Pinch Grip Training',               region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Theraband Finger Extension',   en:'Theraband Finger Extension',        region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Maintien poignet neutre (iso)',en:'Neutral Wrist Isometric Hold',      region:'P',  type:'Iso',  phase:'1'},
  {fr:'Opposition pouce-doigts',      en:'Thumb Opposition Exercises',        region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Intrinsic Hand Exercises',     en:'Intrinsic Hand Exercises',          region:'P',  type:'Mono', phase:'1+2'},
  {fr:'Wrist CARs (mobilité)',        en:'Wrist CARs',                        region:'P',  type:'Mob',  phase:'1'},
  // RACHIS LOMBAIRE
  {fr:'Soulevé de terre (lombaire)',  en:'Deadlift',                          region:'L',  type:'Poly', phase:'2+3'},
  {fr:'Soulevé de terre roumain (lombaire)',en:'Romanian Deadlift',           region:'L',  type:'Poly', phase:'1+2'},
  {fr:'Back extension machine',       en:'Back Extension / Hyperextension',   region:'L',  type:'Mono', phase:'1+2'},
  {fr:'Bird-Dog',                     en:'Bird-Dog',                          region:'L',  type:'Iso',  phase:'1'},
  {fr:'Good morning (lombaire)',      en:'Good Morning',                      region:'L',  type:'Poly', phase:'1+2'},
  {fr:'Kettlebell Swing',             en:'Kettlebell Swing',                  region:'L',  type:'Poly', phase:'2+3'},
  {fr:'Planche (gainage lombaire)',   en:'Plank',                             region:'L',  type:'Iso',  phase:'1+2'},
  {fr:'Hip Hinge (apprentissage)',    en:'Hip Hinge – Technique',             region:'L',  type:'Mob',  phase:'1'},
  {fr:'Rotation lombaire contrôlée',  en:'Lumbar Rotation – Controlled',      region:'L',  type:'Mob',  phase:'1'},
  {fr:'Flexion lombaire active',      en:'Active Lumbar Flexion',             region:'L',  type:'Mob',  phase:'1'},
  {fr:'Extension lombaire isométrique',en:'Lumbar Extension Isometric',       region:'L',  type:'Iso',  phase:'1'},
  {fr:'Jefferson Curl',               en:'Jefferson Curl',                    region:'L',  type:'Poly', phase:'1+2'},
  {fr:'Carré des lombes latéral',     en:'Lateral Bend / QL',                 region:'L',  type:'Mono', phase:'1+2'},
  {fr:'Pallof Press (lombaire)',      en:'Cable Rotation / Pallof Press',     region:'L',  type:'Iso',  phase:'1+2'},
  {fr:'McKenzie extension',           en:'McKenzie Press-Up',                 region:'L',  type:'Mob',  phase:'1'},
  {fr:'Cat-Camel (mobilité)',         en:'Cat-Cow Stretch',                   region:'L',  type:'Mob',  phase:'1'},
  {fr:'Reverse Hyperextension',       en:'Reverse Hyperextension',            region:'L',  type:'Mono', phase:'1+2'},
  // RACHIS THORACIQUE
  {fr:'W-Y-T prone (thoracique)',     en:'W-Y-T Raises – Prone',              region:'T',  type:'Poly', phase:'1+2'},
  {fr:'Rotation thoracique quadrupède',en:'Thoracic Rotation – Quadruped',   region:'T',  type:'Mob',  phase:'1'},
  {fr:'Extension thoracique foam roller',en:'Thoracic Extension – Foam Roller',region:'T', type:'Mob', phase:'1'},
  {fr:'Rotation thoracique assise',   en:'Seated Thoracic Rotation',          region:'T',  type:'Mob',  phase:'1'},
  {fr:'Face Pull (thoracique)',       en:'Face Pull',                         region:'T',  type:'Poly', phase:'1+2'},
  {fr:'Rowing (thoracique)',          en:'Seated Row',                        region:'T',  type:'Poly', phase:'1+2'},
  {fr:'Band Pull-Apart (thoracique)', en:'Band Pull-Apart',                   region:'T',  type:'Mono', phase:'1+2'},
  {fr:'Prone Cobra',                  en:'Prone Cobra',                       region:'T',  type:'Iso',  phase:'1'},
  {fr:'Superman thoracique',          en:'Thoracic Superman',                 region:'T',  type:'Iso',  phase:'1+2'},
  {fr:'Open Book (mobilité)',         en:'Open Book Stretch',                 region:'T',  type:'Mob',  phase:'1'},
  {fr:'Extension thoracique active',  en:'Active Thoracic Extension',         region:'T',  type:'Mob',  phase:'1'},
  {fr:'Rétraction scapulaire iso',    en:'Scapular Retraction Hold',          region:'T',  type:'Iso',  phase:'1'},
  {fr:'Tirage poitrine prise large (thor)',en:'Wide Grip Lat Pulldown',       region:'T',  type:'Poly', phase:'1+2'},
  // RACHIS CERVICAL
  {fr:'Chin Tuck (flexion profonde)', en:'Deep Cervical Flexion – Chin Tuck', region:'Cv', type:'Iso',  phase:'1'},
  {fr:'Flexion cervicale isométrique',en:'Isometric Cervical Flexion',        region:'Cv', type:'Iso',  phase:'1+2'},
  {fr:'Extension cervicale isométrique',en:'Isometric Cervical Extension',    region:'Cv', type:'Iso',  phase:'1+2'},
  {fr:'Rotation cervicale isométrique',en:'Isometric Cervical Rotation',      region:'Cv', type:'Iso',  phase:'1+2'},
  {fr:'Inclinaison latérale iso (cervical)',en:'Isometric Lateral Flexion',   region:'Cv', type:'Iso',  phase:'1+2'},
  {fr:'Shrug (renforcement cervical)',en:'Dumbbell Shrug',                    region:'Cv', type:'Mono', phase:'1+2'},
  {fr:'Extension cervicale GHD',      en:'Neck Extension – GHD',              region:'Cv', type:'Mono', phase:'1+2'},
  {fr:'Rotation cervicale active (CARs)',en:'Active Cervical Rotation – CARs',region:'Cv', type:'Mob',  phase:'1'},
  {fr:'Flexion-extension cervicale (CARs)',en:'Cervical Flexion-Extension CARs',region:'Cv',type:'Mob', phase:'1'},
  {fr:'Semi-épineux isolation',       en:'Semi-Spinalis Strengthening',       region:'Cv', type:'Iso',  phase:'1+2'},
  {fr:'Renforcement SCM',             en:'SCM Strengthening',                 region:'Cv', type:'Iso',  phase:'1+2'},
  {fr:'Mobilité sous-occipitaux',     en:'Sub-Occipital Release',             region:'Cv', type:'Mob',  phase:'1'},
  {fr:'Exercice oculomoteur cervical',en:'Cervico-Ocular Exercise',           region:'Cv', type:'Iso',  phase:'1'},
  // TRONC & GAINAGE
  {fr:'Planche frontale',             en:'Plank / Front Plank',               region:'Tr', type:'Iso',  phase:'1+2'},
  {fr:'Planche latérale',             en:'Side Plank',                        region:'Tr', type:'Iso',  phase:'1+2'},
  {fr:'Planche latérale abduction',   en:'Side Plank with Hip Abduction',     region:'Tr', type:'Iso',  phase:'1+2'},
  {fr:'Planche dynamique shoulder tap',en:'Dynamic Plank – Shoulder Taps',   region:'Tr', type:'Iso',  phase:'1+2'},
  {fr:'Dead Bug',                     en:'Dead Bug',                          region:'Tr', type:'Iso',  phase:'1+2'},
  {fr:'Bird Dog (tronc)',             en:'Bird-Dog',                          region:'Tr', type:'Iso',  phase:'1'},
  {fr:'Hollow Body Hold',             en:'Hollow Body Hold',                  region:'Tr', type:'Iso',  phase:'1+2'},
  {fr:'Crunch',                       en:'Crunch',                            region:'Tr', type:'Mono', phase:'1+2'},
  {fr:'Crunch inverse',               en:'Reverse Crunch',                    region:'Tr', type:'Mono', phase:'1+2'},
  {fr:'Russian Twist',                en:'Russian Twist',                     region:'Tr', type:'Poly', phase:'1+2'},
  {fr:'Pallof Press',                 en:'Pallof Press',                      region:'Tr', type:'Iso',  phase:'1+2'},
  {fr:'Rollout (roue abdominale)',     en:'Ab Wheel Rollout',                  region:'Tr', type:'Iso',  phase:'2+3'},
  {fr:'Mountain Climbers',            en:'Mountain Climbers',                 region:'Tr', type:'Poly', phase:'2+3'},
  {fr:'Hanging Leg Raise',            en:'Hanging Leg Raise',                 region:'Tr', type:'Mono', phase:'2+3'},
  {fr:'Decline Sit-Up',               en:'Decline Sit-Up',                    region:'Tr', type:'Mono', phase:'1+2'},
  {fr:'RKC Plank',                    en:'RKC Plank',                         region:'Tr', type:'Iso',  phase:'2+3'},
  {fr:'Cable Woodchop',               en:'Cable Woodchop',                    region:'Tr', type:'Poly', phase:'1+2'},
  {fr:'Sit-Up',                       en:'Sit-Up',                            region:'Tr', type:'Mono', phase:'1+2'},
  {fr:'Extended Plank (haute)',       en:'Extended Plank / Planche haute',    region:'Tr', type:'Iso',  phase:'1+2'},
  {fr:'Rotation médecine ball',       en:'Medicine Ball Rotation',            region:'Tr', type:'Poly', phase:'2+3'},
  {fr:'Cable Crunch',                 en:'Cable Crunch',                      region:'Tr', type:'Mono', phase:'1+2'},
  {fr:'Dragon Flag',                  en:'Dragon Flag',                       region:'Tr', type:'Iso',  phase:'3'},
  {fr:'Turkish Get-Up',               en:'Turkish Get-Up',                    region:'Tr', type:'Poly', phase:'2+3'},
  {fr:'Suitcase Carry',               en:'Suitcase Carry',                    region:'Tr', type:'Iso',  phase:'1+2'},
  {fr:'Farmers Walk',                en:'Farmers Walk / Carry',             region:'Tr', type:'Iso',  phase:'1+2'},
  {fr:'Hollow Rock',                  en:'Hollow Rock',                       region:'Tr', type:'Iso',  phase:'2+3'},
];
